### PR TITLE
Fixes #3 - allow multiline strings that have the first line non-empty.

### LINKED ISSUE #3: simple_po_parser throws an error on multiline strings which do not start with an empty string
We have a valid po file generated from Weblate:

```screen
❯ msgfmt -c i18n/zammad.zh-cn.po
❯ echo $?
0
```

It contains such multiline strings, which are obviously valid:

```gettext
msgid ""
"By default, the follow-up check is done via the subject of an email. This "
"setting lets you add more fields for which the follow-up check will be "
"executed."
msgstr "默认情况下，通过电子邮件的主题进行跟进检查。这个设置允许你增加更多的字段执行"
"跟进检查。"
```

But they cause the following error:

```
SimplePoParser::ParserError: SimplePoParser::ParserErrorSyntax error in lines
Syntax error in msgctxt
Syntax error in msgid
Syntax error in msgstr
Unexpected content after expected message end "\"跟进检"
Parseing result before error: '{:reference=>"db/seeds/settings.rb", :msgid=>["", "By default, the follow-up check is done via the subject of an email. This ", "setting lets you add more fields for which the follow-up check will be ", "executed."], :msgstr=>"默认情况下，通过电子邮件的主题进行跟进检查。这个设置允许你增加更多的字段执行"}'
SimplePoParser filtered backtrace: SimplePoParser::ParserError
/usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:179:in msgstr'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:134:inmsgid'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:114:in msgctxt'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:51:inlines'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:75:in comment'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:49:inlines'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser/parser.rb:25:in parse'
    from /usr/local/rvm/gems/ruby-2.7.4/gems/simple_po_parser-1.1.5/lib/simple_po_parser.rb:19:inparse_message'
    
```

It seems that such lines are (incorrectly?) expected to be having final white space. Similar multiline strings which contain trailing spaces are processed correctly.

Any help would be appreciated.

### PR DESCRIPTION
**Pull request by mgruner**
This changes the detection of multiline strings to not rely on an empty first string `""`, but instead the presence of another string on the next line (starting with `"`).

### CODE REVIEW

**Comment by dfherr** [comment]
Looks good.

A few things though:
* could you please change the test texts to something generic (english -> english) rather than the texts from your app and chinese translation? I would like the strings to be readable and somewhat meaningful and not chinese characters in here unless it's explicitly to test for unicode/chinese characers. See https://github.com/experteer/simple_po_parser/blob/master/spec/simple_po_parser/fixtures/simple_entry.po as referece
*  ~~The comment ontop the multiline method needs to be updated~~ (edit: ah you removed it. missed that. Maybe writing that it's indicated by the next line starting with a quote would be nicer) https://github.com/experteer/simple_po_parser/blob/b0ab9f76a12273b13869fd7f44231253d116ee8a/lib/simple_po_parser/parser.rb#L268
* Can you please benchmark/time the current version vs your new version on https://github.com/experteer/simple_po_parser/blob/master/test/benchmark.po I'm a bit worried about peek performance and maybe it makes sense to hide this behind an option to only take the boolean hit on every line rather than a peek (which creates a copy of a string, if I skimmed it correctly in the C source)

**Comment by mgruner** [comment]
@dfherr all changes applied as suggested. Let me know if this is ok.

For the benchmark, I executed `rake parser:benchmark` locally, but with 10000 iterations rather than 100. It seems to become only insignificantly slower with the changes of this PR.

```
 THIS PR

 Rehearsal -------------------------------------------
Parser:   8.883388   0.186883   9.070271 (  9.070439)
---------------------------------- total: 9.070271sec

              user     system      total        real
Parser:   8.849168   0.172060   9.021228 (  9.021489)

MASTER BRANCH

Rehearsal -------------------------------------------
Parser:   8.711592   0.157095   8.868687 (  8.868976)
---------------------------------- total: 8.868687sec

              user     system      total        real
Parser:   8.685205   0.154006   8.839211 (  8.839386)
```

Thanks!

**Comment by dfherr** [comment]
Looks good. Gonna test myself tomorrow and then merge/release if everything also looks fine for me locally.

I actually totally forgot I added a benchmark command to the Rakefile 😆 

Thanks for your work!

**Comment by mgruner** [comment]
Thanks @dfherr!

**Comment by mgruner** [comment]
@dfherr there is one place that I probably overlooked. The invocation of `previous_multiline` still uses the old scheme with first empty line. Would you have a recommendation for fixing this as well?

**Comment by mgruner** [comment]
@dfherr added in b5ccb45426df4fbac2ce7c8b0e0a70719891a668, hope this works for you.

**Comment by mgruner** [comment]
@dfherr can you perhaps give an estimate when you may be able to merge and release this fix? 🙏

**Comment by dfherr** [comment]
So, got some time to run local tests and check out the profiler. Performance hit seems to be somewhere in the ballpark of 1-2%. That's certainly not too bad, so I'm gonna go ahead and merge.

Thanks for your contribution!

**Pull request merged**
